#!/bin/bash


if [ $# == 1 ]; then
	echo "Clear current remote info..."
	git remote remove origin
    git remote -v

    echo "Set new remote info... git remote add origin git@gitjoe:joelee-kr/"$1".git"
    git remote add origin git@gitjoe:joelee-kr/"$1".git
    git remote -v
else
    echo "MUST NEED repo_name"
fi
